### PR TITLE
fix: Use Amazon Linux 2 provided runtime

### LINKED ISSUE #320: Update Lambda runtime from Go 1.x (Deprecated) to custom runtime on Amazon Linux 2
## Problem:
Amazon announced the end of support for Go 1.x runtime and the lambdas deployed with cdk-ecr-deployment running on go 1.x runtime will no longer receive support from December 31, 2023 and we will not longer be able to deploy new functions from January 30, 2024.

> We are ending support for the Go 1.x runtime in AWS Lambda, in line with Amazon Linux AMI end of maintenance support on December 31, 2023. Lambda continues to support the Go programming language, using the provided.al2 runtime. Using the provided.al2 runtime offers several benefits over the go1.x runtime, including support for AWS Graviton2 processors and a streamlined implementation with a smaller deployment package and faster function invoke path. For more information, see our blog post. As described in the Lambda runtime support policy, end of support for language runtimes in Lambda happens in two stages. Starting December 31, 2023, Lambda will no longer apply security patches and other updates to the Go 1.x runtime used by Lambda functions, and functions using Go 1.x will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Go 1.x runtime. Starting January 30, 2024, you will no longer be able to update existing functions using the Go 1.x runtime. We recommend that you upgrade your existing Go 1.x functions to the provided.al2 runtime before December 31, 2023.

Reference:
https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/

## Request:
Update the runtime to provided.al2 runtime as mentioned by AWS

### PR DESCRIPTION
**Pull request by SamStephens**
The Go runtime will shortly be end of life, so change over to the AL2 runtime.

Fixes #320 

This is a direct copy of https://github.com/cdklabs/cdk-ecr-deployment/pull/323.

I've not been able to do any real testing. `npx test` appears to pass.

I tried to deploy the sample application as per README.md via `NO_PREBUILT_LAMBDA=1 npx cdk deploy -a "npx ts-node -P tsconfig.dev.json --prefer-ts-exts test/example.ecr-deployment.ts"`, but it appears this no longer works.

```
$ NO_PREBUILT_LAMBDA=1 npx cdk deploy -a "npx ts-node -P tsconfig.dev.json --prefer-ts-exts test/example.ecr-deployment.ts"
/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
test/example.ecr-deployment.ts:4:23 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

4 import * as path from 'path';
                        ~~~~~~
test/example.ecr-deployment.ts:13:8 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

13 } from 'aws-cdk-lib';
          ~~~~~~~~~~~~~
test/example.ecr-deployment.ts:29:28 - error TS2304: Cannot find name '__dirname'.

29       directory: path.join(__dirname, 'docker'),
                              ~~~~~~~~~

    at createTSError (/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/home/sam/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  diagnosticCodes: [ 2307, 2307, 2304 ]
}

Subprocess exited with error 1
```

I'd test using my application that consumes this package, but it's a Python package, and I don't know how to generate a Python library from this package.

### CODE REVIEW

**Comment by scanlonp** [comment]
Getting on this today.

**Review by scanlonp — CHANGES_REQUESTED** [review]
Tested this out and it fails since asset/main is empty. I do not think we should change the name in Dockerfile.

**Comment by learner1unknown** [comment]
Curious as to when this will be merged ? Do you need some help ?

**Comment by SamStephens** [comment]
@scanlonp I won't be back at work until next week, I'll look at this then.

@learner1unknown you're welcome to pick this up and take it across the line if you want to.

**Comment by SamStephens** [comment]
@scanlonp apologies for the delay. It seems clear from the source file still being named `main.go` that you're right, and the change from `main` to `bootstrap` should not have been made.

I've hopefully fixed things, with the usual caveat that I cannot test this.

**Comment by scanlonp** [comment]
@SamStephens yup, I will run this again.

**Comment by scanlonp** [comment]
@SamStephens, I am not super familiar with this module. When I build locally, I cannot get the lambda main to be non-empty. I will see if this is a problem isolated to this pull, but from my initial testing, it is the same for the main branch of the module. Any ideas?

**Comment by SamStephens** [comment]
Okay, now I understand a bit more what is going on, some more fundamental changes are needed.

I [managed to get the test example running](https://github.com/cdklabs/cdk-ecr-deployment/issues/419) and I've learned some more about how this works.

Even with [the change I based this on](https://github.com/cdklabs/cdk-ecr-deployment/pull/323), they're still using the base image public.ecr.aws/sam/build-go1.x:latest, which is deprecated at the end of the year when the Go runtime is.

Instead it should be using an Amazon Linux base image with the aws-lambda-go/lambda package.

The rename of main to bootstrap you called out earlier will have been to do with how Custom Lambda runtimes work. I think rather than this rename, the right thing is to use the aws-lambda-go/lambda package.

I think at this point I'm probably going to close out this pull request, and start with a fresh one.

**Pull request closed without merging**
