### PR TITLE
feat: support JSON Credentials as repo secret

### LINKED ISSUE #900: Support Non-PlainText Secret Format for Container Repository Login
Hello, we are using this library to copy containers from a private container repository (Artifactory) to AWS ECS. We would like to re-use our existing secrets rather than creating something new for this functionality. Specifically, we already have secrets to allow for ECS to authenticate with a private registry based on the following documentation:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html

This requires that the secret be a JSON object with "username" and "password" properties. Would it be possible to update the library to support reading a secret of this type, object, rather than plain-text?

`{
  "username" : "privateRegistryUsername",
  "password" : "privateRegistryPassword"
}`

### PR DESCRIPTION
**Pull request by cbentkowski**
Fixes #900

Added new functionality to GetCredsType in utils.go to parse JSON Username/Password in this format:
`{ "username": "someusername", "password": "somepassword" }`

Added new function, GetJSONSecret to parse and return the JSON Username/Password above to utils.go.

Updated parseCreds in main.go to look for SECRET_JSON and call the GetJSONSecret and return the creds.

Corrected spelling of unknown in error return of parseCreds in main.go.

Tests pass in utils_test.go.

### CODE REVIEW

**Comment by cbentkowski** [comment]
I apologize if I named the pull request/branch incorrectly. This is my very first one to a public repository.

**Review by mrgrain — CHANGES_REQUESTED** [review]
This looks great! Thank you.

One thing though. I'm not 100% sure I understand what exactly this new feature is covering. Is it adding support for stringified JSON in the [`creds` property](https://github.com/cdklabs/cdk-ecr-deployment/blob/main/src/index.ts#L108)? Or for JSON in the SecretsManager Secret? Or for both?

From the code, I _think_ this PR currently only adds supports for stringified JSON in `creds`, but I might be wrong. However I also _think_ the linked issue is talking about JSON support inside the SecretsManager Secret. Could you check that? I reckon this PR would be a huge step to that, but we would need a little bit more work before we can close the issue.

And a couple minor notes:

- Once the above is resolved, please update the docs [here](https://github.com/cdklabs/cdk-ecr-deployment/blob/main/src/index.ts#L108) to describe the newly supported format(s).
- Let's add a test case for `GetJSON`. I know the other types don't have tests, but they are also much simpler.

**Comment by cbentkowski** [comment]
Based on #900, I was going just for stringified JSON in the `creds` property. I can add a comment on #900 to see if they are wanting JSON support inside SecretsManager and if so I can add that. I'll also work on the test for GetJSON and update the docs later today.

**Comment by mrgrain** [comment]
> Based on #900, I was going just for stringified JSON in the `creds` property. I can add a comment on #900 to see if they are wanting JSON support inside SecretsManager and if so I can add that. I'll also work on the test for GetJSON and update the docs later today.

That's perfect, thank you!

**Comment by mrgrain** [comment]
> Ok, similar to the ARN credentials that it already accepts, but the return from the ARN will be JSON formatted text. I've got a JSON parser built, but let me work on detecting JSON string formatted credentials from the ARN and see what I can come up with.

https://github.com/cdklabs/cdk-ecr-deployment/issues/900#issuecomment-2445204952

With that, we can either

- merge this PR (with the request small changes), not close #900 and do a follow-up
- or add the requested feature into this PR

Either is fine with me. LMK what you prefer.

**Comment by mrgrain** [comment]
> I actually have the code to detect a JSON string being returned from the `GetSecretValue`. It's the unit tests I'm having an issue with. Trying to mock up the secret client is a pain.

That's awesome! 

IU understand the challenges with mocking. No idea myself how this works in Golang. Alternatively, wrap all the logic that deals with the response from `GetSecretValue` in a helper function and test that.

`GetSecret`

**Comment by cbentkowski** [comment]
I went ahead and pushed the code I have while I continue to work on unit tests. I'll have to come back to it later this afternoon/evening.

**Comment by mrgrain** [comment]
@cbentkowski Thanks for your work so far. Anything I can help with to get this wrapped up?

**Comment by Hi-Fi** [comment]
Maybe this could be typed also on construct side.

I had similar thing included to other PR (https://github.com/cdklabs/cdk-ecr-deployment/commit/1eebc0c4695eff3e95e62fbca84519ed2aaf8a60#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR98-R110), but removed it already from there as it's easily creating breaking change.

It doesn't have any lambda side handling, as Lambda already handles secrets when ARN is given.

**Comment by Bbuff101** [comment]
> @mrgrain Sorry, work has gotten busy. I'll try to find some time this afternoon/evening to wrap this up.

@cbentkowski , anything I can help with for this PR, or any questions that might be lingering that I can help answer?

**Comment by cbentkowski** [comment]
I'm sorry. I've had a lot of things come up with work and personal life and unfortunately I don't currently have time to continue working on this.

**Comment by mrgrain** [comment]
> I'm sorry. I've had a lot of things come up with work and personal life and unfortunately I don't currently have time to continue working on this.

All good. Thanks for letting us know.

**Pull request closed without merging**
