### PR TITLE
feat: Allow to use secret with key-value pairs

### LINKED ISSUE #179: Feature request: support key-value secrets
Currently plain text secrets from secrets manager can be used. I think quite often it's easy to collect key-value pair secrets to have e.g. username, password and some tokens separated in single secret.

### PR DESCRIPTION
**Pull request by Hi-Fi**
BREAKING CHANGE: API to define credentials changed

Fixes #179

### CODE REVIEW

**Comment by wchaws** [comment]
Is it ready for review?

**Comment by Hi-Fi** [comment]
> 

I'll try to check this in actual environment still today that it works as expected. So trying to get it ready for review today.

**Comment by Hi-Fi** [comment]
Some issues that needs to be checked still with Golang, so might take a while to find time to focus on those.

**Comment by Hi-Fi** [comment]
@wchaws Now Lambda seemed to work as should, so I think this is ready to be reviewed. Also build works in Docker.

**Comment by Hi-Fi** [comment]
@wchaws Do you have had time to check this?

**Comment by Hi-Fi** [comment]
@wchaws how about this?

**Comment by wchaws** [comment]
> @wchaws Do you have had time to check this?

@Hi-Fi Sorry for the late reply. I was so busy for the last few months and didn't have time to review your PR until now.
Overall, your PR looks great except missing some unit test for `main.go`(I know it might be hard to test main.go, since `main.go` depends on SecretsManager).

**Comment by Hi-Fi** [comment]
> > @wchaws Do you have had time to check this?
> 
> @Hi-Fi Sorry for the late reply. I was so busy for the last few months and didn't have time to review your PR until now.
> Overall, your PR looks great except missing some unit test for `main.go`(I know it might be hard to test main.go, since `main.go` depends on SecretsManager).
> 

If remember correctly, I checked unit tests for that but it would require some refactoring to mock those secrets manager calls. But I can try to recheck those.

**Comment by Hi-Fi** [comment]
@wchaws I added testing for secretsmanager now. I didn't add mocking to existing tests that were skipped, even same approach could be used for those to mock out e.g. s3.

**Review by wchaws — APPROVED** [review]
LGTM

**Comment by wchaws** [comment]
Hi @Hi-Fi, First, thanks for your contribution. But since this PR is blocking the sub-sequential release, I think I have to revert this commit. Besides that, I've been getting security alerts for quite some time now. Since our company mandates that these security vulnerabilities be solved, I think there are some issues with the current design. I will re-propose a new design to avoid receiving a lot of security vulnerabilities from go dependencies. The main idea is to download the skopeo cli tool directly instead of building go projects from scratch. I hope you can understand!

**Pull request merged**
