### PR TITLE
fix: bump allowed major version

### PR DESCRIPTION
**Pull request by Hi-Fi**
Fixes releasing of main branch which bumps major version

### CODE REVIEW

**Comment by Hi-Fi** [comment]
@wchaws This is needed for release, or then rewriting the history in main to keep major in v2.

**Comment by wchaws** [comment]
> This is needed for release, or then rewriting the history in main to keep major in v2.

But this will leave a version of v3.0.0 in npm. Currently, I couldn't figure out any butter solution.

**Comment by Hi-Fi** [comment]
> > This is needed for release, or then rewriting the history in main to keep major in v2.
> 
> But this will leave a version of v3.0.0 in npm.

I think there's no 3.0.0 in npm as action failed before publishing (https://www.npmjs.com/package/cdk-ecr-deployment). So if history is rewritten and Breaking change removed, 2.x version is released including break in the credential usage.

**Comment by mrgrain** [comment]
Change was reverted. We stay on the v2 line for now.

**Pull request closed without merging**
